import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "magic text",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Link
          className="absolute top-4 right-4"
          href="https://github.com/debugtheworldbot/text-encode"
          target="_blank"
        >
          <Image
            alt="github"
            width={40}
            height={40}
            src="https://nextjs.org/icons/github.svg"
          />
        </Link>
        {children}
        <ToastContainer />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
